const state=JSON.parse(localStorage.getItem('pocketplan-state')||'null')||{balance:0,spending:[],income:[],subs:[],ious:[],goal:{name:'New headphones',target:180,saved:0}};
state.income=state.income||[];
state.theme=state.theme||'normal';
if(state.balance===1248.5&&state.spending.length===0&&state.income.length===0&&state.subs.length===0&&state.ious.length===0&&state.goal.saved===0)state.balance=0;
let editingIndex=null;
const $=s=>document.querySelector(s); const money=n=>'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function persist(){localStorage.setItem('pocketplan-state',JSON.stringify(state));render()}
function daysUntil(date){const d=new Date(date+'T00:00:00'),now=new Date(); now.setHours(0,0,0,0); return Math.ceil((d-now)/86400000)}
function render(){
 const spent=state.spending.reduce((a,x)=>a+x.amount,0); $('#balanceValue').textContent=money(state.balance); $('#spentValue').textContent=money(spent); $('#purchaseCount').textContent=state.spending.length; $('#balanceChange').textContent=money(spent); $('#safeValue').textContent=money(Math.max(0,state.balance-spent)); $('#safeMeter').style.width=state.balance>0?Math.min(100,Math.max(8,(state.balance-spent)/state.balance*100))+'%':'0%';
 const rows=state.spending.map((x,i)=>`<tr><td><div class="item-cell"><span class="item-dot">${x.emoji}</span>${x.name}</div></td><td>${x.date}</td><td><span class="category">${x.category}</span></td><td class="amount">-${money(x.amount)}</td><td><button class="edit-expense-btn" data-edit-index="${i}" aria-label="Edit ${x.name}">Edit</button><button class="delete-row-btn" data-expense-delete="${i}">Delete</button></td></tr>`).join(''); $('#spendingList').innerHTML=rows||'<tr class="empty-row"><td colspan="5">No purchases yet — add one above!</td></tr>';
 const sorted=state.subs.map((x,i)=>({x,i})).sort((a,b)=>new Date(a.x.date)-new Date(b.x.date)); const next=sorted.find(({x})=>daysUntil(x.date)>=0)||sorted[0]; $('#nextSubValue').textContent=next?money(next.x.amount):'—'; $('#nextSubName').textContent=next?next.x.name:'Add a bill to see it here'; $('#nextSubDue').textContent=next?`${daysUntil(next.x.date)===0?'Due today':daysUntil(next.x.date)+' days to go'}`:'Nothing due yet'; $('#subscriptionList').innerHTML=sorted.map(({x,i})=>{let d=daysUntil(x.date);return `<div class="list-row"><div class="list-icon">${x.emoji}</div><div class="list-main"><strong>${x.name}</strong><small>${new Date(x.date+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div><div class="list-end"><strong>${money(x.amount)}</strong><small>${d<0?'Past due':d===0?'Due today':d+' days'}</small><div class="row-actions"><button class="edit-row-btn" data-sub-edit="${i}">Edit</button><button class="delete-row-btn" data-sub-delete="${i}">Delete</button></div></div></div>`}).join('')||'<div class="empty-state">No bills yet — add one to see your countdown.</div>';
 $('#iouList').innerHTML=state.ious.map((x,i)=>{let d=daysUntil(x.date);return `<div class="list-row"><div class="list-icon">🤝</div><div class="list-main"><strong>${x.name}</strong><small>Pay by ${new Date(x.date+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div><div class="list-end"><strong>${money(x.amount)}</strong><small>${d<0?'Overdue':d===0?'Today':d+' days'}</small><div class="row-actions"><button class="edit-row-btn" data-iou-edit="${i}">Edit</button><button class="delete-row-btn" data-iou-delete="${i}">Delete</button></div></div></div>`}).join('')||'<div class="empty-state">No one to pay back — you’re all caught up!</div>';
 const g=state.goal,p=Math.min(100,Math.round(g.saved/g.target*100)),coins=Math.floor(g.saved),coinsNeeded=Math.ceil(Math.max(0,g.target-g.saved)); $('#goalName').textContent=g.name;$('#goalSaved').textContent=money(g.saved).replace('.00','');$('#goalTarget').textContent=money(g.target).replace('.00','');$('#goalPercent').textContent=p+'%';$('#goalMeter').style.width=p+'%';$('#goalPiggy').style.left=Math.min(92,Math.max(8,p))+'%';$('#goalRemaining').textContent=g.saved>=g.target?'You did it! 🎉':'You need '+money(g.target-g.saved)+' more';$('#coinCount').textContent=`🪙 ${coins} ${coins===1?'coin':'coins'} in piggy`;$('#coinNeed').textContent=coinsNeeded===0?'All the coins you need! 🎉':`${coinsNeeded} ${coinsNeeded===1?'coin':'coins'} to go`;
}
function toggle(id){$(id).classList.toggle('hidden')}
function applyTheme(){let pirate=state.theme==='pirate';document.body.classList.toggle('pirate',pirate);$('#themeToggle').textContent=pirate?'🌈 Normal mode':'🏴‍☠️ Pirate mode';$('#welcomeTitle').innerHTML=pirate?'Ahoy, matey! 🏴‍☠️':'Welcome back <span>👋</span>';}
function openNewSpend(){editingIndex=null;$('#saveSpend').textContent='Save';toggle('#spendForm');}
$('#openSpendForm').onclick=openNewSpend; $('#quickAddTop').onclick=()=>{$('#spending').scrollIntoView({behavior:'smooth'});editingIndex=null;$('#saveSpend').textContent='Save';$('#spendForm').classList.remove('hidden');$('#spendName').focus()}; $('#openSubForm').onclick=()=>toggle('#subForm'); $('#openIouForm').onclick=()=>toggle('#iouForm');
$('#saveSpend').onclick=()=>{let n=$('#spendName').value.trim(),a=Number($('#spendAmount').value),category=$('#spendCategory').value;if(!n||!a)return;if(editingIndex===null){state.spending.unshift({name:n,amount:a,category,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'}),emoji:{Food:'🍎',Fun:'🎮',School:'📚',Travel:'🚌',Other:'🛍️'}[category]});state.balance-=a}else{let old=state.spending[editingIndex];state.balance+=old.amount-a;old.name=n;old.amount=a;old.category=category;old.emoji={Food:'🍎',Fun:'🎮',School:'📚',Travel:'🚌',Other:'🛍️'}[category];editingIndex=null}$('#saveSpend').textContent='Save';$('#spendName').value='';$('#spendAmount').value='';toggle('#spendForm');persist()};
$('#saveSub').onclick=()=>{let n=$('#subName').value.trim(),a=Number($('#subAmount').value),d=$('#subDate').value;if(!n||!a||!d)return;state.subs.push({name:n,amount:a,date:d,emoji:'◉'});['subName','subAmount','subDate'].forEach(id=>$('#'+id).value='');toggle('#subForm');persist()};
$('#saveIou').onclick=()=>{let n=$('#iouName').value.trim(),a=Number($('#iouAmount').value),d=$('#iouDate').value;if(!n||!a||!d)return;state.ious.push({name:n,amount:a,date:d});['iouName','iouAmount','iouDate'].forEach(id=>$('#'+id).value='');toggle('#iouForm');persist()};
$('#spendingList').onclick=e=>{let button=e.target.closest('[data-edit-index]');if(!button)return;editingIndex=Number(button.dataset.editIndex);let item=state.spending[editingIndex];$('#spendName').value=item.name;$('#spendAmount').value=item.amount;$('#spendCategory').value=item.category;$('#saveSpend').textContent='Update';$('#spendForm').classList.remove('hidden');$('#spendName').focus()};
$('#spendingList').addEventListener('click',e=>{let button=e.target.closest('[data-expense-delete]');if(!button)return;let i=Number(button.dataset.expenseDelete),item=state.spending[i];if(!confirm(`Delete expense "${item.name}"?`))return;state.balance+=item.amount;state.spending.splice(i,1);editingIndex=null;persist()});
$('#subscriptionList').addEventListener('click',e=>{let edit=e.target.closest('[data-sub-edit]'),del=e.target.closest('[data-sub-delete]');if(edit){let i=Number(edit.dataset.subEdit),item=state.subs[i],name=prompt('Subscription name:',item.name),amount=prompt('Amount:',item.amount),date=prompt('Charge date (YYYY-MM-DD):',item.date);if(name&&amount&&date){item.name=name.trim();item.amount=Number(amount);item.date=date;persist()}}else if(del){let i=Number(del.dataset.subDelete);if(confirm(`Delete subscription "${state.subs[i].name}"?`)){state.subs.splice(i,1);persist()}}});
$('#iouList').addEventListener('click',e=>{let edit=e.target.closest('[data-iou-edit]'),del=e.target.closest('[data-iou-delete]');if(edit){let i=Number(edit.dataset.iouEdit),item=state.ious[i],name=prompt('Who do you owe?',item.name),amount=prompt('Amount:',item.amount),date=prompt('Due date (YYYY-MM-DD):',item.date);if(name&&amount&&date){item.name=name.trim();item.amount=Number(amount);item.date=date;persist()}}else if(del){let i=Number(del.dataset.iouDelete);if(confirm(`Delete IOU for "${state.ious[i].name}"?`)){state.ious.splice(i,1);persist()}}});
$('#resetAmounts').onclick=()=>{if(!confirm('Reset all expense, income, subscription, IOU, balance, and savings amounts?'))return;state.balance=0;state.spending=[];state.income=[];state.subs=[];state.ious=[];state.goal.saved=0;editingIndex=null;persist()};
$('#editGoal').onclick=()=>{ $('#goalForm').classList.toggle('hidden'); $('#goalNameInput').value=state.goal.name;$('#goalTargetInput').value=state.goal.target}; $('#saveGoal').onclick=()=>{let n=$('#goalNameInput').value.trim(),t=Number($('#goalTargetInput').value);if(n&&t){state.goal.name=n;state.goal.target=t;if(state.goal.saved>=t)state.goal.saved=0;$('#goalForm').classList.add('hidden');persist()}}; $('#addToGoal').onclick=()=>{let amount=Number(prompt('How much did you save?'));if(amount>0){state.goal.saved+=amount;state.balance-=amount;if(state.goal.saved>=state.goal.target){state.goal.saved=0;alert('Goal complete! Your savings progress has reset for your next goal.')}persist()}};
$('#openMoneyForm').onclick=()=>{toggle('#moneyForm');if(!$('#moneyForm').classList.contains('hidden'))$('#moneyAmount').focus()};
$('#saveMoney').onclick=()=>{let a=Number($('#moneyAmount').value),source=$('#moneySource').value.trim();if(!a||a<=0||!source)return;state.balance+=a;state.income.unshift({amount:a,source,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})});$('#moneyAmount').value='';$('#moneySource').value='';toggle('#moneyForm');persist()};
$('#themeToggle').onclick=()=>{state.theme=state.theme==='pirate'?'normal':'pirate';applyTheme();persist()};
applyTheme();
render();
