const state=JSON.parse(localStorage.getItem('pocketplan-state')||'null')||{balance:1248.5,spending:[],income:[],subs:[],ious:[],goal:{name:'New headphones',target:180,saved:0}};
state.income=state.income||[];
const $=s=>document.querySelector(s); const money=n=>'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function persist(){localStorage.setItem('pocketplan-state',JSON.stringify(state));render()}
function daysUntil(date){const d=new Date(date+'T00:00:00'),now=new Date(); now.setHours(0,0,0,0); return Math.ceil((d-now)/86400000)}
function render(){
 const spent=state.spending.reduce((a,x)=>a+x.amount,0); $('#balanceValue').textContent=money(state.balance); $('#spentValue').textContent=money(spent); $('#purchaseCount').textContent=state.spending.length; $('#balanceChange').textContent=money(spent); $('#safeValue').textContent=money(Math.max(0,state.balance-spent)); $('#safeMeter').style.width=Math.min(100,Math.max(8,(state.balance-spent)/state.balance*100))+'%';
 const rows=state.spending.map(x=>`<tr><td><div class="item-cell"><span class="item-dot">${x.emoji}</span>${x.name}</div></td><td>${x.date}</td><td><span class="category">${x.category}</span></td><td class="amount">-${money(x.amount)}</td></tr>`).join(''); $('#spendingList').innerHTML=rows||'<tr class="empty-row"><td colspan="4">No purchases yet — add one above!</td></tr>';
 const sorted=[...state.subs].sort((a,b)=>new Date(a.date)-new Date(b.date)); const next=sorted.find(x=>daysUntil(x.date)>=0)||sorted[0]; $('#nextSubValue').textContent=next?money(next.amount):'—'; $('#nextSubName').textContent=next?next.name:'Add your first subscription'; $('#nextSubDue').textContent=next?`${daysUntil(next.date)===0?'Due today':daysUntil(next.date)+' days to go'}`:'No upcoming bills'; $('#subscriptionList').innerHTML=sorted.map(x=>{let d=daysUntil(x.date);return `<div class="list-row"><div class="list-icon">${x.emoji}</div><div class="list-main"><strong>${x.name}</strong><small>${new Date(x.date+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div><div class="list-end"><strong>${money(x.amount)}</strong><small>${d<0?'Past due':d===0?'Due today':d+' days'}</small></div></div>`}).join('')||'<div class="empty-state">Nothing scheduled yet. Add a subscription to see the countdown.</div>';
 $('#iouList').innerHTML=state.ious.map(x=>{let d=daysUntil(x.date);return `<div class="list-row"><div class="list-icon">🤝</div><div class="list-main"><strong>${x.name}</strong><small>Pay by ${new Date(x.date+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div><div class="list-end"><strong>${money(x.amount)}</strong><small>${d<0?'Overdue':d===0?'Today':d+' days'}</small></div></div>`}).join('')||'<div class="empty-state">No IOUs — you’re all caught up!</div>';
 const g=state.goal,p=Math.min(100,Math.round(g.saved/g.target*100)); $('#goalName').textContent=g.name;$('#goalSaved').textContent=money(g.saved).replace('.00','');$('#goalTarget').textContent=money(g.target).replace('.00','');$('#goalPercent').textContent=p+'%';$('#goalMeter').style.width=p+'%';$('#goalRemaining').textContent=g.saved>=g.target?'Goal reached!':money(g.target-g.saved)+' to go';
}
function toggle(id){$(id).classList.toggle('hidden')}
$('#openSpendForm').onclick=()=>toggle('#spendForm'); $('#quickAddTop').onclick=()=>{$('#spending').scrollIntoView({behavior:'smooth'});$('#spendForm').classList.remove('hidden');$('#spendName').focus()}; $('#openSubForm').onclick=()=>toggle('#subForm'); $('#openIouForm').onclick=()=>toggle('#iouForm');
$('#saveSpend').onclick=()=>{let n=$('#spendName').value.trim(),a=Number($('#spendAmount').value);if(!n||!a)return;state.spending.unshift({name:n,amount:a,category:$('#spendCategory').value,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'}),emoji:{Food:'🍎',Fun:'🎮',School:'📚',Travel:'🚌',Other:'🛍️'}[$('#spendCategory').value]});state.balance-=a;$('#spendName').value='';$('#spendAmount').value='';toggle('#spendForm');persist()};
$('#saveSub').onclick=()=>{let n=$('#subName').value.trim(),a=Number($('#subAmount').value),d=$('#subDate').value;if(!n||!a||!d)return;state.subs.push({name:n,amount:a,date:d,emoji:'◉'});['subName','subAmount','subDate'].forEach(id=>$('#'+id).value='');toggle('#subForm');persist()};
$('#saveIou').onclick=()=>{let n=$('#iouName').value.trim(),a=Number($('#iouAmount').value),d=$('#iouDate').value;if(!n||!a||!d)return;state.ious.push({name:n,amount:a,date:d});['iouName','iouAmount','iouDate'].forEach(id=>$('#'+id).value='');toggle('#iouForm');persist()};
$('#editGoal').onclick=()=>{ $('#goalForm').classList.toggle('hidden'); $('#goalNameInput').value=state.goal.name;$('#goalTargetInput').value=state.goal.target}; $('#saveGoal').onclick=()=>{let n=$('#goalNameInput').value.trim(),t=Number($('#goalTargetInput').value);if(n&&t){state.goal.name=n;state.goal.target=t;$('#goalForm').classList.add('hidden');persist()}}; $('#addToGoal').onclick=()=>{let amount=Number(prompt('How much did you save?'));if(amount>0){state.goal.saved+=amount;state.balance-=amount;persist()}};
$('#openMoneyForm').onclick=()=>{toggle('#moneyForm');if(!$('#moneyForm').classList.contains('hidden'))$('#moneyAmount').focus()};
$('#saveMoney').onclick=()=>{let a=Number($('#moneyAmount').value),source=$('#moneySource').value.trim();if(!a||a<=0||!source)return;state.balance+=a;state.income.unshift({amount:a,source,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})});$('#moneyAmount').value='';$('#moneySource').value='';toggle('#moneyForm');persist()};
render();
